-- 1. 프로필 테이블 (Supabase의 기본 auth.users와 1:1 매칭됨)
CREATE TABLE public.profiles (
  id uuid references auth.users not null primary key,
  nickname text not null,
  grade text default '일반' not null,
  stamps integer default 0 not null,
  created_at timestamptz default now() not null
);

-- 2. 메뉴 테이블
CREATE TABLE public.menus (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null,
  category text not null,
  image_url text,
  created_at timestamptz default now() not null
);

-- 3. 쿠폰 테이블 (스탬프 10개 달성 시 발급될 테이블)
CREATE TABLE public.coupons (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  name text not null,
  is_used boolean default false not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz default now() not null
);

-- 4. 주문 테이블
CREATE TABLE public.orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  total_amount integer not null,
  status text default '결제완료' not null,
  created_at timestamptz default now() not null
);

-- 5. 주문 상세 아이템 (어떤 메뉴를 몇 개 시켰는지)
CREATE TABLE public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) not null,
  menu_id bigint references public.menus(id) not null,
  quantity integer not null default 1,
  unit_price integer not null
);

-----------------------------------------------------------
-- 🔒 보안 설정 (RLS - Row Level Security) 
-----------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- 정책: 메뉴는 누구나(비로그인 포함) 조회 가능
CREATE POLICY "누구나 메뉴 조회 가능" ON public.menus FOR SELECT USING (true);

-- 정책: 프로필, 쿠폰, 주문 내역은 로그인한 본인(auth.uid())만 조회 가능
CREATE POLICY "본인 프로필 조회" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "본인 쿠폰 조회" ON public.coupons FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "본인 주문 조회" ON public.orders FOR SELECT TO authenticated USING (auth.uid() = user_id);
